#!/usr/bin/env python3
"""Package exact validated model outputs for the 25-position UI assessment."""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MODERATE = ROOT / "search/runs/capacity-moderate/baseline_atlas.csv"
ADVANCED = ROOT / "search/runs/capacity-refinement-352/output/baseline_atlas.csv"
OUTPUT = ROOT / "public/movement-reference.js"

ADVANCED_IDS = {
    "D1": "refine__sobol__0000447__shoulder_rot__p5",
    "D2": "refine__sobol__0000603__pro_sup__m5",
    "D3": "refine__sobol__0000673__pro_sup__p5",
    "D4": "refine__sobol__0001262__elbow_flexion__m5",
    "D5": "refine__sobol__0001711__shoulder_rot__p2",
    "D6": "refine__sobol__0003073__shoulder_elv__m5",
    "D7": "refine__sobol__0004077__elv_angle__p2",
}

MODERATE_IDS = {
    "M1": "moderate__neutral",
    "M2": "moderate__elbow_45",
    "M3": "moderate__elbow_90",
    "M4": "moderate__forward_30_elbow_90",
    "M5": "moderate__forward_45_elbow_90",
    "M6": "moderate__forward_60_elbow_90",
    "M7": "moderate__scaption_30_elbow_90",
    "M8": "moderate__scaption_45_elbow_90",
    "M9": "moderate__scaption_60_elbow_90",
    "M10": "moderate__side_30_elbow_90",
    "M11": "moderate__side_45_elbow_90",
    "M12": "moderate__side_60_elbow_90",
    "M13": "moderate__rotation_side_external_20",
    "M14": "moderate__rotation_side_external_40",
    "M15": "moderate__rotation_side_internal_20",
    "M16": "moderate__rotation_side_internal_40",
    "M17": "moderate__forearm_pronation_45",
    "M18": "moderate__forearm_supination_45",
}


def load(path: Path) -> tuple[dict[str, dict[str, str]], list[str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = {row["sample_id"]: row for row in reader}
        muscles = [
            field.removeprefix("activation__")
            for field in (reader.fieldnames or [])
            if field.startswith("activation__")
        ]
    return rows, muscles


def main() -> None:
    moderate, moderate_muscles = load(MODERATE)
    advanced, advanced_muscles = load(ADVANCED)
    if moderate_muscles != advanced_muscles or len(moderate_muscles) != 50:
        raise RuntimeError("Expected the same 50-muscle schema in both atlases")

    result: dict[str, object] = {}
    for section, mapping, rows in (
        ("progressive-movement", MODERATE_IDS, moderate),
        ("discrimination", ADVANCED_IDS, advanced),
    ):
        for identifier, sample_id in mapping.items():
            row = rows.get(sample_id)
            if row is None or row["usable"] != "1":
                raise RuntimeError(f"Missing usable baseline result: {identifier} / {sample_id}")
            result[identifier] = {
                "section": section,
                "sourceSampleId": sample_id,
                "solverDurationMs": float(row["duration_ms"]),
                "maximumReserveTorqueNm": float(row["max_reserve_torque_nm"]),
                "muscles": [
                    {
                        "name": muscle,
                        "activation": float(row[f"activation__{muscle}"]),
                        "activeActuatorForceN": float(row[f"active_force_n__{muscle}"]),
                    }
                    for muscle in moderate_muscles
                ],
            }

    payload = {
        "schemaVersion": 1,
        "modelId": "MOBL_ARMS_41",
        "modelSha256": "8BF1C3F0DB841DEFAACA2B906DED154A2B1700531B96B491AAB3DBC9A7343289",
        "method": "Exact validated generic-model static equilibrium under gravity only; no external load.",
        "positions": result,
    }
    OUTPUT.write_text(
        "// Generated by search/build_movement_reference.py; do not edit manually.\n"
        "export const MOVEMENT_MODEL_REFERENCE = Object.freeze("
        + json.dumps(payload, separators=(",", ":"))
        + ");\n",
        encoding="utf-8",
    )
    print(json.dumps({"status": "ok", "positions": len(result), "output": str(OUTPUT)}))


if __name__ == "__main__":
    main()
